##
##  @Note: Propiedades principales de la aplicacion
##

# Variables del servidor Tomcat Embedded
server:
  port: ${PORT:8081}
  servlet:
    context-path: /demo
spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/clinica_security?useTimezone=true&serverTimezone=America/El_Salvador&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: orion1993$
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    password: Orion1993Lgge$
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            trust: smtp.gmail.com
          starttls:
            enable: true
    test-connection: false
    username: marlon.f.1993@gmail.com
  thymeleaf:
    cache: false
